### ISSUE TITLE
Yank the current 1.3.4 release package and rerelease with the current main branch code

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/OperationsAndWorkflows#81]
The 1.3.4 release package has a broken [Workflow Schema](https://github.com/NCATSTranslator/OperationsAndWorkflows/blob/1.3.4/schema/workflow.json) pointing to the [Operations v1.3.4](https://standards.ncats.io/workflow/1.3.2/schema) instead of the [Operations v1.3.4 schema](https://standards.ncats.io/workflow/1.3.4/schema).  This needs to be fixed!

Since this project is self contained and doesn't actually release packages to pypi.org (or other external repository), maybe it suffices to simply **_yank_** the **_current 1.3.4 release package_** and **_re-release the 1.3.4 package with the current main branch code_** instead?

**Comment by edeutsch** [comment]
Presumably OP meant 

The 1.3.4 release package has a broken [Workflow Schema](https://github.com/NCATSTranslator/OperationsAndWorkflows/blob/1.3.4/schema/workflow.json) pointing to the [Operations v1.3.2](https://standards.ncats.io/workflow/1.3.2/schema) instead of the [Operations v1.3.4 schema](https://standards.ncats.io/workflow/1.3.4/schema). This needs to be fixed!

**Comment by cbizon** [comment]
I have rereleased, it appears to be fixed.  Reopen if I've missed something....
